name: node

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      # Install dependencies
      - run: yarn install

      # Build and output webpack stats
      - run: yarn build --json webpack-stats.json

      # Upload webpack-stats.json to use on relative-ci.yaml workflow
      - name: Upload webpack stats artifact
        uses: relative-ci/agent-upload-artifact-action@v1
        with:
          webpackStatsFile: ./webpack-stats.json

      # Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: webpack-stats-artifacts
          path: artifacts
