name: node

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      # Install dependencies
      - run: yarn install

      # Build and output webpack stats
      - run: yarn build --json webpack-stats.json

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          webpackStatsFile: ./webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            webpack-stats.json
